### ISSUE TITLE
Issue running the indexer with Magento 2.3.3

### ISSUE THREAD

**Issue by chammedinger** [DivanteLtd/magento2-vsbridge-indexer#163]
We have an issue running the indexer with Magento 2.3.3
With the extension installed we get following error message when running

bin/magento indexer:reindex
or
php bin/magento indexer:reindex vsbridge_taxrule_indexer
php bin/magento indexer:reindex vsbridge_attribute_indexer
php bin/magento indexer:reindex vsbridge_product_indexer
php bin/magento indexer:reindex vsbridge_category_indexer
php bin/magento indexer:reindex vsbridge_cms_block_indexer
php bin/magento indexer:reindex vsbridge_cms_page_indexer
php bin/magento indexer:reindex vsbridge_review_indexer
or
php bin/magento vsbridge:reindex

this always gives us the message:
Cannot instantiate interface Magento\InventoryIndexer\Model\StockIndexTableNameResolverInterface in /magento2/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php:116

**Comment by Hypo386** [comment]
Hi,

I've just run brand new Magento2 instance with sample data deployed to check how vsbridge works with 2.3.3 version.

I can't reproduce this issue since everything works well.

![image](https://user-images.githubusercontent.com/4815371/69798895-87f4e780-11d2-11ea-9c1a-1b59a6020548.png)

Magento 2.3.3
PHP 7.2.16

Module version 1.8.0 installed by composer

![image](https://user-images.githubusercontent.com/4815371/69799183-0fdaf180-11d3-11ea-88f2-07ed72e84833.png)

Elasticsearch data is there

![image](https://user-images.githubusercontent.com/4815371/69799248-3731be80-11d3-11ea-84ca-f90cb5f154af.png)

Issue can be related to particular Magento instance so please check your Magento installation or provide information how to reproduce...

**Comment by chammedinger** [comment]
Okay, thank you for checking this.
Possibly we have an interference with another module.
We will further check this when we go on with the migration process.
(For now we have downgraded to an earlier magento version)

**Comment by afirlejczyk** [comment]
Hi, @Hypo386 - Thanks for checking!
@chammedinger did you also install a second module for msi support ?
https://github.com/DivanteLtd/magento2-vsbridge-indexer-msi

**Comment by chammedinger** [comment]
Yes, I did.
Atm I´m setting up the system on magento 2.2.8 without the msi module.
What exactly does the msi module do?
