### ISSUE TITLE
Too long invalidate redis cache url for mass actions or large amount of products in a shop

### ISSUE THREAD

**Issue by mmularski** [DivanteLtd/magento2-vsbridge-indexer#183]
For now, Redis cache invalidation generates URL with a chain of tags as many as it gets which is a bad idea. 

GET requests in many architectures are cut to some specific length or size which could cause broken request URL or some entities will not be invalidated in Redis cache.

**Comment by afirlejczyk** [comment]
Hi, 
What do you propose as a solution?

If URL exeed max length: 
1) We can push request to flash cache for all products instead.
2) We can push multiple request instead of one

 VSF should probably add support for POST to invalidate cache.

Let me know which option 1) or 2) will be better, both have some advantages/disadvantages.
If url exceed max length of URL

**Comment by mmularski** [comment]
In the last project where I faced this problem, I needed to fix this quite fast, so I decided to divide too long requests into smaller ones(with a configuration in admin panel how much entities per request should be send)

But I think the dream scenario would be rewriting GET to POST

**Comment by afirlejczyk** [comment]
@patzick @pkarw 
Could you plan this?
It would be nice if we can use POST to run invalidate cache 
```
curl http://localhost:3000/invalidate?tag=P1852,C20
```
for VSF and VSF-API.

@mmularski It would be best to use POST, but I don't know when this feature will be available.
Will you be able to do PR with your solution?

**Comment by mmularski** [comment]
Currently, I do not have time for new PRs, but I  try to do it asap
