### ISSUE TITLE
(question) ES6+ support

### ISSUE THREAD

**Issue by undefinederror** [DivanteLtd/magento2-vsbridge-indexer#221]
Hi,
I see that branch 2.x has support for ES6+

1) Is this stable enough for production?
2) When will it be merged into master?
3) What are all the random numbers appended to the indeces? Are they necessary?
```
vue_storefront_catalog_de_at_attribute_1582038134
vue_storefront_catalog_de_at_category_1582038134
vue_storefront_catalog_de_at_cms_block_1582038131
vue_storefront_catalog_de_at_cms_page_1582038132
vue_storefront_catalog_de_at_product_1582038132
vue_storefront_catalog_de_at_review_1582038135
vue_storefront_catalog_de_at_taxrule_1582038135
```

Thank you

**Comment by afirlejczyk** [comment]
Hi,

Changes from 2.x branch won't be merge to master . I plan to have two main branches for supporting ES5 and ES6+.

2.x - for supporting ES6+
1.x - for supporting ES5, 
master and develop branch will be "archived".

Changes in 2.x are not compatible with current version.

I didn't have time to setup everything, but I can create new tag for current 2.x branch.

Little more information are available here:
https://github.com/DivanteLtd/magento2-vsbridge-indexer/pull/147#issuecomment-571744175

`vue_storefront_catalog_de_at_attribute_1582038134` - this is just index names and yes they are necessary (it just a time when index was created). Each index has a clean alias, like: "vue_storefront_catalog_de_at_attribute" - so you can use index alias instead of real index name. If you used mage2vuestofront tool - it works the same way.

Support for aliases was added some time ago:
https://github.com/DivanteLtd/magento2-vsbridge-indexer/pull/131
https://github.com/DivanteLtd/magento2-vsbridge-indexer/pull/138

**Comment by undefinederror** [comment]
Thank you @afirlejczyk
